ALTER TABLE "events"
ADD COLUMN "banner_key" VARCHAR(50) NOT NULL DEFAULT 'COMMUNITY_SCREENING';

ALTER TABLE "events"
ADD CONSTRAINT "events_banner_key_check"
CHECK ("banner_key" IN ('COMMUNITY_SCREENING', 'LIBRARY_SCREENING', 'EVENT_OPERATIONS'));
