const AUTH_AUDIT_EVENTS = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  TOKEN_REFRESH_SUCCESS: "TOKEN_REFRESH_SUCCESS",
  TOKEN_REFRESH_FAILED: "TOKEN_REFRESH_FAILED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  GLOBAL_LOGOUT_SUCCESS: "GLOBAL_LOGOUT_SUCCESS",
  GLOBAL_LOGOUT_FAILED: "GLOBAL_LOGOUT_FAILED",
  PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGE_FAILED",
});

const AUDIT_ACTIONS = Object.freeze({
  SCREENING_RESULT_RECORDED: "SCREENING_RESULT_RECORDED",
  SCREENING_RESULT_CORRECTED: "SCREENING_RESULT_CORRECTED",
  SCREENING_FLAG_ACKNOWLEDGED: "SCREENING_FLAG_ACKNOWLEDGED",
  QR_GENERATED: "QR_GENERATED",
  QR_REVOKED: "QR_REVOKED",
  QR_REISSUED_REVOCATION: "QR_REISSUED_REVOCATION",
  QR_DOWNLOADED: "QR_DOWNLOADED",
  QR_PRINTED: "QR_PRINTED",
  QR_ACCESS_DENIED: "QR_ACCESS_DENIED",
  QR_VERIFIED: "QR_VERIFIED",
  QR_VERIFICATION_DENIED: "QR_VERIFICATION_DENIED",
  QR_VERIFICATION_FAILED: "QR_VERIFICATION_FAILED",
  MANUAL_CHECKIN_PERFORMED: "MANUAL_CHECKIN_PERFORMED",
  SCREENING_SYNC_BATCH: "SCREENING_SYNC_BATCH",
  SCREENING_SYNC_ACTION_APPLIED: "SCREENING_SYNC_ACTION_APPLIED",
  SCREENING_SYNC_ACTION_CONFLICT: "SCREENING_SYNC_ACTION_CONFLICT",
  SCREENING_SYNC_ACTION_FAILED: "SCREENING_SYNC_ACTION_FAILED",
});

const AUTH_AUDIT_EVENT_VALUES = new Set(Object.values(AUTH_AUDIT_EVENTS));

module.exports = { AUTH_AUDIT_EVENTS, AUTH_AUDIT_EVENT_VALUES, AUDIT_ACTIONS };
