-- VSMS database-routine catalog
--
-- The executable definitions are versioned and deployed by Prisma migration:
-- prisma/migrations/20260813040000_add_database_routines/migration.sql
--
-- This catalog intentionally contains no second copy of the routine bodies. A
-- standalone SQL copy previously targeted obsolete tables such as queue_entry,
-- station_queues, and visual_acuity_results, so it could drift from production.
-- Prisma migrations are now the single deployment authority.
--
-- Deployed routines
-- -----------------
-- FUNCTION  vsms_event_queue_statistics(uuid, timestamptz, timestamptz)
--   Returns PII-free queue counts plus p50/p90 wait and service durations for
--   FR-07 completed-event analytics.
--
-- PROCEDURE sp_vsms_cancel_active_registration_queue(uuid, uuid, timestamptz)
--   Cancels active queue rows when the authorized review service terminates a
--   participant journey. It validates event/registration scope in PostgreSQL.
--
-- TRIGGER FUNCTION vsms_assert_registration_station_scope()
--   Rejects cross-event route, queue-entry, and screening-result relationships.
--
-- TRIGGER FUNCTION vsms_assert_queue_movement_scope()
--   Rejects cross-event source or destination stations in queue movements.
--
-- Runtime adapters
-- ----------------
-- utils/database/databaseRoutines.js
--
-- Verification
-- ------------
-- backend/.vsms/tests/database-routines.integration.test.js
