-- VSMS database-routine catalogue (Keefe)
--
-- This file is documentation only. Do not execute it.
-- Prisma migrations are the sole deployment authority.
--
-- Queue analytics, active-queue cancellation, route completion, and
-- event/station integrity triggers:
--   prisma/migrations/20260814200000_add_database_routines/migration.sql
--
-- Registration routines:
--   prisma/migrations/20260813150100_add_registration_stored_functions/migration.sql
--   prisma/migrations/20260813170000_remove_registration_consent_acknowledgement/migration.sql
--   prisma/migrations/20260814210000_harden_registration_stored_routines/migration.sql
--
-- Screening completeness, reviewed-result immutability, and flag auditing:
--   prisma/migrations/20260814220000_add_screening_stored_routines/migration.sql
--
-- All callable routines use SECURITY INVOKER with a fixed search_path.
-- PUBLIC execution is revoked; runtime grants are defined in
-- prisma/runtime-role.example.sql.
