-- VSMS registration-routine catalogue (Mike)
--
-- This file is documentation only. Do not execute it.
-- Prisma migrations are the sole deployment authority.
--
-- FUNCTION register_participant_for_event(uuid, uuid, uuid, varchar)
-- FUNCTION check_in_event_registration(uuid, uuid, uuid)
-- FUNCTION get_event_registration_summary(uuid)
--   prisma/migrations/20260813150100_add_registration_stored_functions/migration.sql
--   prisma/migrations/20260813170000_remove_registration_consent_acknowledgement/migration.sql
--
-- FUNCTION cancel_event_registration(uuid, uuid, varchar)
--   Atomically cancels registration, revokes active QR passes, promotes the
--   oldest waitlisted registration, and writes status history.
--   prisma/migrations/20260814210000_harden_registration_stored_routines/migration.sql
--
-- Runtime adapter: services/participant/registrationRoutineRepository.js
-- Verification: tests/integration/registration-routines.integration.test.js
