-- VSMS queue and screening-routine catalogue (Nachiketh)
--
-- This file is documentation only. Do not execute it.
-- Prisma migrations are the sole deployment authority.
--
-- FUNCTION vsms_event_queue_statistics(uuid, timestamptz, timestamptz)
-- PROCEDURE sp_vsms_cancel_active_registration_queue(uuid, uuid, timestamptz)
-- FUNCTION vsms_registration_route_complete(uuid, uuid)
-- TRIGGER FUNCTION vsms_assert_registration_station_scope()
-- TRIGGER FUNCTION vsms_assert_queue_movement_scope()
--   prisma/migrations/20260814200000_add_database_routines/migration.sql
--
-- Queue movement, screening writes, clinical policy, RBAC, and actor-aware
-- audit orchestration remain in the Express service layer.
-- Runtime adapter: utils/database/databaseRoutines.js
-- Verification: backend/.vsms/tests/database-routines.integration.test.js
