const { execFile } = require("child_process");
const path = require("path");
const fs = require("fs");
const { createAuditLog } = require("../../utils/logging/audit");

// Dedicated directory for backup dumps in root
const BACKUP_DIR = path.join(__dirname, "../../../backups");

/**
 * OWASP A01/A05: Sanitizes filename inputs to prevent Path Traversal attacks.
 * Only backup files generated by this service are accepted.
 */
function sanitizeFilename(filename) {
    if (typeof filename !== "string") {
        throw new Error("Invalid or unsafe backup file identifier.");
    }

    const safeName = path.basename(filename);

    if (
        safeName !== filename ||
        !/^backup_[\w-]+\.dump$/.test(safeName)
    ) {
        throw new Error("Invalid or unsafe backup file identifier.");
    }

    return safeName;
}

/**
 * Safely fetches DB environment variables without hardcoding secrets.
 */
function getDbEnv() {
    return {
        ...process.env,
        PGPASSWORD:
            process.env.DATABASE_PASSWORD ||
            process.env.DB_PASSWORD,
    };
}

/**
 * Gets the configured database connection values.
 */
function getDatabaseConfig() {
    return {
        dbUser:
            process.env.DATABASE_USER ||
            process.env.DB_USER ||
            "postgres",

        dbHost:
            process.env.DATABASE_HOST ||
            process.env.DB_HOST ||
            "localhost",

        dbPort:
            process.env.DATABASE_PORT ||
            process.env.DB_PORT ||
            "5432",

        dbName:
            process.env.DATABASE_NAME ||
            process.env.DB_NAME ||
            "vsms",
    };
}

/**
 * Ensures the backup directory exists.
 */
function ensureBackupDirectory() {
    if (!fs.existsSync(BACKUP_DIR)) {
        fs.mkdirSync(BACKUP_DIR, {
            recursive: true,
            mode: 0o700,
        });
    }
}

/**
 * List all available database backups in storage.
 */
exports.listBackups = async () => {
    ensureBackupDirectory();

    const files = fs.readdirSync(BACKUP_DIR);

    return files
        .filter((file) => /^backup_[\w-]+\.dump$/.test(file))
        .map((file) => {
            const filePath = path.join(BACKUP_DIR, file);
            const stats = fs.statSync(filePath);

            return {
                backupId: file,
                sizeBytes: stats.size,
                createdAt: stats.birthtime,
            };
        });
};

/**
 * Triggers a database backup execution via pg_dump.
 *
 * Security:
 * - Uses execFile instead of exec.
 * - Arguments are passed separately.
 * - No shell command is constructed.
 * - Prevents shell command injection.
 */
exports.createBackup = async (
    { description },
    actorId,
    context
) => {
    ensureBackupDirectory();

    const timestamp = new Date()
        .toISOString()
        .replace(/[:.]/g, "-");

    const filename = `backup_${timestamp}.dump`;
    const filePath = path.join(BACKUP_DIR, filename);

    const {
        dbUser,
        dbHost,
        dbPort,
        dbName,
    } = getDatabaseConfig();

    const args = [
        "-h",
        dbHost,
        "-p",
        dbPort,
        "-U",
        dbUser,
        "-F",
        "c",
        "-f",
        filePath,
        dbName,
    ];

    return new Promise((resolve, reject) => {
        execFile(
            "pg_dump",
            args,
            {
                env: getDbEnv(),
                maxBuffer: 1024 * 1024 * 50,
            },
            async (error, stdout, stderr) => {
                if (error) {
                    console.error("pg_dump error:", stderr);

                    // Remove a potentially incomplete backup.
                    try {
                        if (fs.existsSync(filePath)) {
                            fs.unlinkSync(filePath);
                        }
                    } catch (cleanupError) {
                        console.error(
                            "Failed to remove incomplete backup:",
                            cleanupError
                        );
                    }

                    return reject(
                        new Error(
                            "Failed to execute database backup process."
                        )
                    );
                }

                await createAuditLog({
                    userId: actorId,
                    action: "SYSTEM_BACKUP_CREATED",
                    entityName: "System",
                    entityId: filename,
                    newValue: {
                        filename,
                        description,
                    },
                    context,
                }).catch(console.error);

                resolve({
                    message: "Backup created successfully.",
                    backupId: filename,
                });
            }
        );
    });
};

/**
 * Validates and retrieves safe absolute path for direct file downloads.
 */
exports.getBackupFilePath = async (backupId) => {
    const safeFilename = sanitizeFilename(backupId);
    const filePath = path.join(BACKUP_DIR, safeFilename);

    if (!fs.existsSync(filePath)) {
        throw new Error("Backup file not found.");
    }

    return filePath;
};

/**
 * Restores database from a given dump file using pg_restore.
 *
 * Security:
 * - Validates the backup filename.
 * - Prevents path traversal.
 * - Uses execFile instead of exec.
 * - Passes the backup path as a separate argument.
 * - No shell command is constructed.
 */
exports.restoreBackup = async (
    backupId,
    actorId,
    context
) => {
    const safeFilename = sanitizeFilename(backupId);
    const filePath = path.join(BACKUP_DIR, safeFilename);

    if (!fs.existsSync(filePath)) {
        throw new Error("Target backup file does not exist.");
    }

    const {
        dbUser,
        dbHost,
        dbPort,
        dbName,
    } = getDatabaseConfig();

    const args = [
        "-h",
        dbHost,
        "-p",
        dbPort,
        "-U",
        dbUser,
        "-d",
        dbName,
        "--clean",
        filePath,
    ];

    return new Promise((resolve, reject) => {
        execFile(
            "pg_restore",
            args,
            {
                env: getDbEnv(),
                maxBuffer: 1024 * 1024 * 50,
            },
            async (error, stdout, stderr) => {
                if (error) {
                    console.error("pg_restore error:", stderr);

                    return reject(
                        new Error(
                            "Failed to execute database restore process."
                        )
                    );
                }

                await createAuditLog({
                    userId: actorId,
                    action: "SYSTEM_BACKUP_RESTORED",
                    entityName: "System",
                    entityId: safeFilename,
                    newValue: {
                        filename: safeFilename,
                    },
                    context,
                }).catch(console.error);

                resolve({
                    message:
                        "Database restored successfully from backup.",
                });
            }
        );
    });
};

/**
 * Deletes a local backup dump file from storage.
 *
 * Security:
 * - Validates the supplied backup identifier.
 * - Prevents path traversal.
 */
exports.deleteBackup = async (
    backupId,
    actorId,
    context
) => {
    const safeFilename = sanitizeFilename(backupId);
    const filePath = path.join(BACKUP_DIR, safeFilename);

    if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
    }

    await createAuditLog({
        userId: actorId,
        action: "SYSTEM_BACKUP_DELETED",
        entityName: "System",
        entityId: safeFilename,
        context,
    }).catch(console.error);

    return {
        message: "Backup file deleted successfully.",
    };
};